version: '3'

networks:
  laravel:

services:
  nginx:
    image: dhairya137/foodma-codecanyon:nginx
    container_name: nginx
    ports:
      - "8088:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: dhairya137/foodma-codecanyon:mysql
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports: 
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev 
      SERVICE_NAME: mysql
    networks:
      - laravel
  
  php:
    image: dhairya137/foodma-codecanyon:v1
    container_name: php
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    ports:
      - "9000:9000"
    networks:
      - laravel